title: Personal Portfolio
description: A showcase of my projects, skills, and professional experience

# Build configuration
sass:
  style: compressed
  sourcemap: never

# Site settings
locale: "en-US"
name: "Generative AI Engineer"
url: "https://nayyarcoder.github.io"
repository: "nayyarcoder/nayyarcoder.github.io"

# Social links
github_username: nayyarcoder
linkedin_username: ai-engineer

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# GitHub Pages settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

# Theme settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
